import React, { useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet,
  TextInput, Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useThemeColors } from '@/components/ui/useThemeColors';
import { useShoppingStore } from '@/store/useShoppingStore';
import { useIngredientsStore } from '@/store/useIngredientsStore';
import { usePantryStore } from '@/store/usePantryStore';
import { ShoppingItemRow } from '@/components/ShoppingItemRow';
import { EmptyState } from '@/components/ui/EmptyState';
import { ConfirmDialog } from '@/components/ui/ConfirmDialog';
import { Toast } from '@/components/ui/Toast';
import { shareShoppingList } from '@/services/backupService';
import { INGREDIENT_CATEGORIES } from '@/types';

type GroupBy = 'category' | 'none';

export default function ShoppingScreen({ isEmbedded }: { isEmbedded?: boolean }) {
  const colors = useThemeColors();
  const activeList = useShoppingStore(s => s.activeList);
  const items = useShoppingStore(s => s.items);
  const isLoading = useShoppingStore(s => s.isLoading);
  const markBought = useShoppingStore(s => s.markBought);
  const unmarkBought = useShoppingStore(s => s.unmarkBought);
  const deleteItem = useShoppingStore(s => s.deleteItem);
  const clearBought = useShoppingStore(s => s.clearBought);
  const completeList = useShoppingStore(s => s.completeList);
  const generateSmartList = useShoppingStore(s => s.generateSmartList);
  const createList = useShoppingStore(s => s.createList);
  const addItem = useShoppingStore(s => s.addItem);
  const ingredients = useIngredientsStore(s => s.ingredients);
  const addPantryItem = usePantryStore(s => s.addItem);

  const [groupBy, setGroupBy] = useState<GroupBy>('category');
  const [clearConfirm, setClearConfirm] = useState(false);
  const [completeConfirm, setCompleteConfirm] = useState(false);
  const [toast, setToast] = useState<{ visible: boolean; message: string; type: 'success' | 'error' }>({ visible: false, message: '', type: 'success' });
  const [showAddManual, setShowAddManual] = useState(false);
  const [manualName, setManualName] = useState('');
  const [manualQty, setManualQty] = useState('1');
  const [manualUnit, setManualUnit] = useState('unidad');

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ visible: true, message, type });
  };

  const pendingCount = items.filter(i => !i.isBought).length;
  const boughtCount = items.filter(i => i.isBought).length;

  const groupedItems = () => {
    if (groupBy === 'none') return [{ title: 'Todos los productos', data: items }];
    const catMap = new Map<string, typeof items>();
    for (const item of items) {
      const cat = item.category;
      if (!catMap.has(cat)) catMap.set(cat, []);
      catMap.get(cat)!.push(item);
    }
    return Array.from(catMap.entries()).map(([cat, data]) => ({
      title: INGREDIENT_CATEGORIES.find(c => c.value === cat)?.label ?? cat,
      emoji: INGREDIENT_CATEGORIES.find(c => c.value === cat)?.emoji ?? '📦',
      data: data.sort((a, b) => Number(a.isBought) - Number(b.isBought)),
    }));
  };

  const handleShare = async () => {
    if (!activeList) return;
    try {
      await shareShoppingList(activeList.id);
    } catch (e) {
      showToast('Error al compartir la lista', 'error');
    }
  };

  const handleCompleteList = async () => {
    // Añadir productos comprados al almacén
    const boughtItems = items.filter(i => i.isBought);
    for (const item of boughtItems) {
      await addPantryItem({
        ingredientId: item.ingredientId ?? null,
        customName: item.name,
        quantity: item.boughtQuantity ?? item.neededQuantity,
        unit: item.unit,
        minQuantity: null,
        location: 'despensa',
        purchaseDate: new Date().toISOString().split('T')[0],
        expiryDate: null,
        brand: null,
        price: item.price ?? null,
        notes: null,
        isOpen: false,
        openedDate: null,
        batchId: null,
      });
    }
    await completeList();
    showToast(`${boughtItems.length} productos añadidos al almacén`);
    setCompleteConfirm(false);
  };

  const handleAddManual = async () => {
    if (!manualName.trim()) return;
    await addItem({
      shoppingListId: '',
      ingredientId: null,
      name: manualName.trim(),
      neededQuantity: parseFloat(manualQty) || 1,
      unit: manualUnit as any,
      category: 'otros',
      sourceRecipes: '[]',
      isAutoGenerated: false,
      isBought: false,
      boughtQuantity: null,
      price: null,
      store: null,
      notes: null,
    });
    setManualName('');
    setManualQty('1');
    setShowAddManual(false);
    showToast('Producto añadido a la lista');
  };

  const Wrapper = isEmbedded ? View : SafeAreaView;
  const wrapperProps = isEmbedded ? { style: [styles.safe, { backgroundColor: colors.background }] } : { style: [styles.safe, { backgroundColor: colors.background }], edges: ['top'] as any };

  return (
    <Wrapper {...wrapperProps}>
      {/* Header */}
      <View style={[styles.header, { backgroundColor: colors.backgroundCard, borderBottomColor: colors.separator }, isEmbedded && { paddingTop: 0, paddingBottom: 8, borderBottomWidth: 0 }]}>
        {!isEmbedded ? <Text style={[styles.title, { color: colors.text }]}>Lista de la compra</Text> : <View style={{flex: 1}} />}
        <View style={styles.headerActions}>
          <TouchableOpacity
            style={styles.iconBtn}
            onPress={handleShare}
            accessibilityRole="button"
            accessibilityLabel="Compartir lista"
          >
            <Ionicons name="share-outline" size={22} color={colors.primary} />
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.iconBtn, { marginRight: 4 }]}
            onPress={async () => {
              await generateSmartList();
              showToast('Lista generada inteligentemente');
            }}
            accessibilityRole="button"
            accessibilityLabel="Generar lista inteligente"
          >
            <Ionicons name="sparkles" size={22} color={colors.primary} />
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.addBtn, { backgroundColor: colors.primary }]}
            onPress={() => setShowAddManual(true)}
            accessibilityRole="button"
            accessibilityLabel="Añadir producto manualmente"
          >
            <Ionicons name="add" size={22} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </View>

      {/* Stats bar */}
      {activeList && (
        <View style={[styles.statsBar, { backgroundColor: colors.backgroundCard, borderBottomColor: colors.separator }]}>
          <View style={styles.statItem}>
            <Text style={[styles.statNum, { color: colors.primary }]}>{pendingCount}</Text>
            <Text style={[styles.statLabel, { color: colors.textSecondary }]}>Pendientes</Text>
          </View>
          <View style={[styles.statDivider, { backgroundColor: colors.separator }]} />
          <View style={styles.statItem}>
            <Text style={[styles.statNum, { color: colors.success }]}>{boughtCount}</Text>
            <Text style={[styles.statLabel, { color: colors.textSecondary }]}>Comprados</Text>
          </View>
          <View style={[styles.statDivider, { backgroundColor: colors.separator }]} />
          <View style={styles.statItem}>
            <Text style={[styles.statNum, { color: colors.text }]}>{items.length}</Text>
            <Text style={[styles.statLabel, { color: colors.textSecondary }]}>Total</Text>
          </View>
        </View>
      )}

      {/* Añadir manual inline */}
      {showAddManual && (
        <View style={[styles.addManualCard, { backgroundColor: colors.backgroundCard, borderColor: colors.primary }]}>
          <TextInput
            style={[styles.addManualInput, { backgroundColor: colors.backgroundInput, borderColor: colors.border, color: colors.text }]}
            placeholder="Nombre del producto"
            placeholderTextColor={colors.textPlaceholder}
            value={manualName}
            onChangeText={setManualName}
            autoFocus
            accessibilityLabel="Nombre del producto a añadir"
          />
          <View style={styles.addManualRow}>
            <TextInput
              style={[styles.addManualQty, { backgroundColor: colors.backgroundInput, borderColor: colors.border, color: colors.text }]}
              placeholder="1"
              placeholderTextColor={colors.textPlaceholder}
              keyboardType="numeric"
              value={manualQty}
              onChangeText={setManualQty}
              accessibilityLabel="Cantidad"
            />
            <TouchableOpacity style={[styles.addManualBtn, { backgroundColor: colors.primary }]} onPress={handleAddManual}>
              <Text style={styles.addManualBtnText}>Añadir</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={() => setShowAddManual(false)}>
              <Ionicons name="close" size={22} color={colors.textTertiary} />
            </TouchableOpacity>
          </View>
        </View>
      )}

      {/* Lista vacía */}
      {items.length === 0 ? (
        <EmptyState
          icon="cart-outline"
          title="Lista vacía"
          description="Planifica tu menú semanal para generar automáticamente la lista de la compra"
        >
          <View style={{ flexDirection: 'row', gap: 10, marginTop: 16 }}>
            <TouchableOpacity
              style={[styles.planBtn, { backgroundColor: colors.primary, flex: 1, alignItems: 'center' }]}
              onPress={() => router.push('/(tabs)/plan')}
            >
              <Text style={styles.planBtnText}>Ir al Plan</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.planBtn, { backgroundColor: colors.text, flex: 1, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 }]}
              onPress={async () => {
                await generateSmartList();
                showToast('Lista inteligente generada');
              }}
            >
              <Ionicons name="sparkles" size={16} color={colors.background} />
              <Text style={[styles.planBtnText, { color: colors.background }]}>Auto-Generar</Text>
            </TouchableOpacity>
          </View>
        </EmptyState>
      ) : (
        <>
          <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
            {groupedItems().map(group => (
              <View key={group.title}>
                <Text style={[styles.groupHeader, { color: colors.textSecondary, backgroundColor: colors.background }]}>
                  {(group as any).emoji} {group.title}
                </Text>
                <View style={[styles.groupCard, { backgroundColor: colors.backgroundCard }]}>
                  {group.data.map(item => (
                    <ShoppingItemRow
                      key={item.id}
                      item={item}
                      onToggleBought={() => item.isBought ? unmarkBought(item.id) : markBought(item.id)}
                      onDelete={() => deleteItem(item.id)}
                    />
                  ))}
                </View>
              </View>
            ))}
            <View style={{ height: 100 }} />
          </ScrollView>

          {/* Acciones inferiores */}
          <View style={[styles.bottomActions, { backgroundColor: colors.backgroundCard, borderTopColor: colors.separator }]}>
            {boughtCount > 0 && (
              <TouchableOpacity
                style={[styles.actionBtn, { backgroundColor: colors.errorSurface }]}
                onPress={() => setClearConfirm(true)}
                accessibilityRole="button"
                accessibilityLabel="Limpiar productos comprados"
              >
                <Ionicons name="trash-outline" size={18} color={colors.error} />
                <Text style={[styles.actionBtnText, { color: colors.error }]}>Limpiar comprados</Text>
              </TouchableOpacity>
            )}
            {boughtCount > 0 && (
              <TouchableOpacity
                style={[styles.actionBtn, { backgroundColor: colors.primary }]}
                onPress={() => setCompleteConfirm(true)}
                accessibilityRole="button"
                accessibilityLabel="Finalizar compra y añadir al almacén"
              >
                <Ionicons name="checkmark-done" size={18} color="#FFFFFF" />
                <Text style={[styles.actionBtnText, { color: '#FFFFFF' }]}>Finalizar compra</Text>
              </TouchableOpacity>
            )}
          </View>
        </>
      )}

      <ConfirmDialog
        visible={clearConfirm}
        title="Limpiar productos comprados"
        message="¿Eliminar todos los productos marcados como comprados de la lista?"
        confirmText="Limpiar"
        destructive
        onConfirm={async () => { await clearBought(); setClearConfirm(false); }}
        onCancel={() => setClearConfirm(false)}
      />

      <ConfirmDialog
        visible={completeConfirm}
        title="Finalizar compra"
        message={`Se añadirán ${boughtCount} productos comprados a tu almacén. ¿Continuar?`}
        confirmText="Finalizar y añadir"
        onConfirm={handleCompleteList}
        onCancel={() => setCompleteConfirm(false)}
      />

      <Toast visible={toast.visible} message={toast.message} type={toast.type} onHide={() => setToast(t => ({ ...t, visible: false }))} />
    </Wrapper>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  title: { fontSize: 24, fontWeight: '800' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  addBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsBar: {
    flexDirection: 'row',
    padding: 14,
    justifyContent: 'space-around',
    borderBottomWidth: 1,
  },
  statItem: { alignItems: 'center' },
  statNum: { fontSize: 22, fontWeight: '800' },
  statLabel: { fontSize: 12, fontWeight: '500', marginTop: 2 },
  statDivider: { width: 1, marginVertical: 4 },
  addManualCard: {
    margin: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    gap: 10,
  },
  addManualInput: {
    height: 44,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    borderWidth: 1,
  },
  addManualRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  addManualQty: {
    width: 70,
    height: 44,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    borderWidth: 1,
    textAlign: 'center',
  },
  addManualBtn: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addManualBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  scroll: { padding: 16 },
  groupHeader: {
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  groupCard: {
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  bottomActions: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    borderTopWidth: 1,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  actionBtnText: { fontSize: 14, fontWeight: '700' },
  planBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  planBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
});
