import { create } from 'zustand';
import type { ShoppingList, ShoppingItem, IngredientCategory, Unit } from '@/types';
import { executeQuery, executeRun, executeFirst } from '@/database/db';
import { v4 as uuidv4 } from 'uuid';
import { useMealPlanStore } from './useMealPlanStore';
import { useRecipesStore } from './useRecipesStore';
import { usePantryStore } from './usePantryStore';
import { useIngredientsStore } from './useIngredientsStore';
import { aggregateIngredients, calculateShoppingList } from '@/services/shoppingListCalculator';

interface ShoppingState {
  activeList: ShoppingList | null;
  items: ShoppingItem[];
  isLoading: boolean;
  error: string | null;
  loadActiveList: () => Promise<void>;
  createList: (name: string, weekStart?: string) => Promise<string>;
  addItem: (item: Omit<ShoppingItem, 'id' | 'createdAt'>) => Promise<string>;
  updateItem: (id: string, updates: Partial<ShoppingItem>) => Promise<void>;
  markBought: (id: string, boughtQty?: number) => Promise<void>;
  unmarkBought: (id: string) => Promise<void>;
  deleteItem: (id: string) => Promise<void>;
  clearBought: () => Promise<void>;
  completeList: () => Promise<void>;
  getItemsByCategory: () => Record<string, ShoppingItem[]>;
  generateSmartList: () => Promise<void>;
}

export const useShoppingStore = create<ShoppingState>((set, get) => ({
  activeList: null,
  items: [],
  isLoading: false,
  error: null,

  loadActiveList: async () => {
    set({ isLoading: true, error: null });
    try {
      const listRow = await executeFirst<Record<string, unknown>>(
        'SELECT * FROM shopping_lists WHERE is_active = 1 ORDER BY created_at DESC LIMIT 1'
      );

      if (!listRow) {
        set({ activeList: null, items: [], isLoading: false });
        return;
      }

      const list = mapRowToList(listRow);
      const itemRows = await executeQuery<Record<string, unknown>>(
        'SELECT * FROM shopping_items WHERE shopping_list_id = ? ORDER BY category, name',
        [list.id]
      );

      set({ activeList: list, items: itemRows.map(mapRowToItem), isLoading: false });
    } catch (e) {
      set({ error: String(e), isLoading: false });
    }
  },

  createList: async (name, weekStart) => {
    // Desactivar lista anterior
    await executeRun('UPDATE shopping_lists SET is_active = 0 WHERE is_active = 1');
    const id = uuidv4();
    const now = new Date().toISOString();
    await executeRun(
      'INSERT INTO shopping_lists (id, name, week_start, is_active, created_at, updated_at) VALUES (?, ?, ?, 1, ?, ?)',
      [id, name, weekStart ?? null, now, now]
    );
    await get().loadActiveList();
    return id;
  },

  addItem: async (item) => {
    const list = get().activeList;
    if (!list) {
      // Auto-crear lista si no existe
      await get().createList('Lista de la compra');
    }
    const activeList = get().activeList!;
    const id = uuidv4();
    const now = new Date().toISOString();
    await executeRun(
      `INSERT INTO shopping_items (id, shopping_list_id, ingredient_id, name, needed_quantity, unit, category, source_recipes, is_auto_generated, is_bought, bought_quantity, price, store, notes, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id, activeList.id, item.ingredientId ?? null, item.name, item.neededQuantity,
        item.unit, item.category, item.sourceRecipes, item.isAutoGenerated ? 1 : 0,
        item.isBought ? 1 : 0, item.boughtQuantity ?? null, item.price ?? null,
        item.store ?? null, item.notes ?? null, now,
      ]
    );
    set(state => ({
      items: [...state.items, { ...item, id, createdAt: now }],
    }));
    return id;
  },

  updateItem: async (id, updates) => {
    const current = get().items.find(i => i.id === id);
    if (!current) return;
    await executeRun(
      `UPDATE shopping_items SET name = ?, needed_quantity = ?, unit = ?, is_bought = ?, bought_quantity = ?, price = ?, store = ?, notes = ? WHERE id = ?`,
      [
        updates.name ?? current.name, updates.neededQuantity ?? current.neededQuantity,
        updates.unit ?? current.unit, updates.isBought !== undefined ? (updates.isBought ? 1 : 0) : (current.isBought ? 1 : 0),
        updates.boughtQuantity ?? current.boughtQuantity ?? null,
        updates.price ?? current.price ?? null, updates.store ?? current.store ?? null,
        updates.notes ?? current.notes ?? null, id,
      ]
    );
    set(state => ({
      items: state.items.map(i => i.id === id ? { ...i, ...updates } : i),
    }));
  },

  markBought: async (id, boughtQty) => {
    await get().updateItem(id, { isBought: true, boughtQuantity: boughtQty });
  },

  unmarkBought: async (id) => {
    await get().updateItem(id, { isBought: false, boughtQuantity: null });
  },

  deleteItem: async (id) => {
    await executeRun('DELETE FROM shopping_items WHERE id = ?', [id]);
    set(state => ({ items: state.items.filter(i => i.id !== id) }));
  },

  clearBought: async () => {
    const list = get().activeList;
    if (!list) return;
    await executeRun('DELETE FROM shopping_items WHERE shopping_list_id = ? AND is_bought = 1', [list.id]);
    set(state => ({ items: state.items.filter(i => !i.isBought) }));
  },

  completeList: async () => {
    const list = get().activeList;
    if (!list) return;
    const now = new Date().toISOString();
    await executeRun(
      'UPDATE shopping_lists SET is_active = 0, completed_at = ?, updated_at = ? WHERE id = ?',
      [now, now, list.id]
    );
    set(state => ({
      activeList: state.activeList ? { ...state.activeList, isActive: false, completedAt: now } : null,
    }));
  },

  getItemsByCategory: () => {
    const grouped: Record<string, ShoppingItem[]> = {};
    for (const item of get().items) {
      const cat = item.category;
      if (!grouped[cat]) grouped[cat] = [];
      grouped[cat].push(item);
    }
    return grouped;
  },

  generateSmartList: async () => {
    set({ isLoading: true });
    try {
      const mealPlanState = useMealPlanStore.getState();
      const recipesState = useRecipesStore.getState();
      const pantryState = usePantryStore.getState();
      const ingredientsState = useIngredientsStore.getState();

      if (!mealPlanState.mealPlan) {
        set({ isLoading: false });
        return;
      }

      // 1. Gather all recipes for meals that haven't been prepared
      const plannedMeals = mealPlanState.plannedMeals.filter(m => !m.isPrepared);
      const recipeIngredientsInput = [];
      
      for (const meal of plannedMeals) {
        if (!meal.recipeId) continue;
        const recipe = recipesState.getById(meal.recipeId);
        if (recipe) {
          recipeIngredientsInput.push({
            recipeName: recipe.name,
            servings: recipe.servings,
            scaleFactor: meal.servings / recipe.servings,
            ingredients: recipe.ingredients,
          });
        }
      }

      // 2. Aggregate requirements
      const requirements = aggregateIngredients(recipeIngredientsInput);

      // 3. Calculate what's missing
      const calculation = calculateShoppingList(
        requirements,
        pantryState.items,
        ingredientsState.conversions
      );

      // 4. Create new list and add items
      if (calculation.items.length > 0) {
        await get().createList('Compra Inteligente', mealPlanState.mealPlan.weekStart);
        
        for (const missing of calculation.items) {
          await get().addItem({
            shoppingListId: '', // Added by addItem automatically
            ingredientId: missing.ingredientId ?? null,
            name: missing.name,
            neededQuantity: missing.missing,
            unit: missing.unit,
            category: missing.category,
            sourceRecipes: JSON.stringify(missing.sourceRecipes),
            isAutoGenerated: true,
            isBought: false,
            boughtQuantity: null,
            price: null,
            store: null,
            notes: null,
          });
        }
      }
      set({ isLoading: false });
    } catch (e) {
      set({ error: String(e), isLoading: false });
    }
  },
}));

function mapRowToList(row: Record<string, unknown>): ShoppingList {
  return {
    id: String(row.id),
    name: String(row.name),
    weekStart: row.week_start ? String(row.week_start) : null,
    isActive: Boolean(Number(row.is_active ?? 0)),
    totalEstimated: row.total_estimated != null ? Number(row.total_estimated) : null,
    totalActual: row.total_actual != null ? Number(row.total_actual) : null,
    completedAt: row.completed_at ? String(row.completed_at) : null,
    createdAt: String(row.created_at ?? ''),
    updatedAt: String(row.updated_at ?? ''),
  };
}

function mapRowToItem(row: Record<string, unknown>): ShoppingItem {
  return {
    id: String(row.id),
    shoppingListId: String(row.shopping_list_id),
    ingredientId: row.ingredient_id ? String(row.ingredient_id) : null,
    name: String(row.name),
    neededQuantity: Number(row.needed_quantity ?? 0),
    unit: String(row.unit ?? 'unidad') as Unit,
    category: String(row.category ?? 'otros') as IngredientCategory,
    sourceRecipes: String(row.source_recipes ?? '[]'),
    isAutoGenerated: Boolean(Number(row.is_auto_generated ?? 0)),
    isBought: Boolean(Number(row.is_bought ?? 0)),
    boughtQuantity: row.bought_quantity != null ? Number(row.bought_quantity) : null,
    price: row.price != null ? Number(row.price) : null,
    store: row.store ? String(row.store) : null,
    notes: row.notes ? String(row.notes) : null,
    createdAt: String(row.created_at ?? ''),
  };
}
