import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useThemeColors } from './ui/useThemeColors';
import { ShoppingItem } from '@/types';
import { formatQuantity } from '@/services/unitConversion';

interface ShoppingItemRowProps {
  item: ShoppingItem;
  onToggleBought: () => void;
  onPress?: () => void;
  onDelete?: () => void;
}

export function ShoppingItemRow({ item, onToggleBought, onPress, onDelete }: ShoppingItemRowProps) {
  const colors = useThemeColors();
  const sources = JSON.parse(item.sourceRecipes || '[]') as string[];

  return (
    <TouchableOpacity
      style={[styles.row, { borderBottomColor: colors.separator }]}
      onPress={onPress}
      activeOpacity={0.7}
      accessibilityRole="button"
      accessibilityLabel={`${item.name}. ${item.neededQuantity} ${item.unit}. ${item.isBought ? 'Comprado' : 'Pendiente'}.`}
    >
      <TouchableOpacity
        onPress={onToggleBought}
        style={[styles.checkbox, {
          backgroundColor: item.isBought ? colors.success : 'transparent',
          borderColor: item.isBought ? colors.success : colors.border,
        }]}
        accessibilityRole="checkbox"
        accessibilityState={{ checked: item.isBought }}
        accessibilityLabel={item.isBought ? 'Marcar como no comprado' : 'Marcar como comprado'}
      >
        {item.isBought && <Ionicons name="checkmark" size={14} color="#FFFFFF" />}
      </TouchableOpacity>

      <View style={styles.content}>
        <Text style={[styles.name, { color: item.isBought ? colors.textTertiary : colors.text, textDecorationLine: item.isBought ? 'line-through' : 'none' }]}>
          {item.name}
        </Text>
        {sources.length > 0 && (
          <Text style={[styles.sources, { color: colors.textTertiary }]} numberOfLines={1}>
            Para: {sources.join(', ')}
          </Text>
        )}
      </View>

      <View style={styles.right}>
        <Text style={[styles.quantity, { color: item.isBought ? colors.textTertiary : colors.primary }]}>
          {formatQuantity(item.neededQuantity, item.unit)}
        </Text>
        {item.isAutoGenerated && (
          <View style={[styles.autoBadge, { backgroundColor: colors.secondarySurface }]}>
            <Ionicons name="flash" size={10} color={colors.secondary} />
          </View>
        )}
      </View>

      {onDelete && (
        <TouchableOpacity
          onPress={onDelete}
          style={styles.deleteBtn}
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
          accessibilityRole="button"
          accessibilityLabel="Eliminar item"
        >
          <Ionicons name="close" size={18} color={colors.textTertiary} />
        </TouchableOpacity>
      )}
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    gap: 12,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: { flex: 1 },
  name: { fontSize: 15, fontWeight: '500' },
  sources: { fontSize: 11, marginTop: 3 },
  right: { alignItems: 'flex-end', gap: 4 },
  quantity: { fontSize: 14, fontWeight: '700' },
  autoBadge: {
    width: 18,
    height: 18,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtn: { paddingLeft: 4 },
});
