import React, { useMemo, useState } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet, Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useThemeColors } from '@/components/ui/useThemeColors';
import { useRecipesStore } from '@/store/useRecipesStore';
import { usePantryStore } from '@/store/usePantryStore';
import { useIngredientsStore } from '@/store/useIngredientsStore';
import { useShoppingStore } from '@/store/useShoppingStore';
import { useSettingsStore } from '@/store/useSettingsStore';
import { ConfirmDialog } from '@/components/ui/ConfirmDialog';
import { Toast } from '@/components/ui/Toast';
import { checkIngredientAvailability, scaleIngredients } from '@/services/shoppingListCalculator';
import { formatQuantity } from '@/services/unitConversion';
import { RECIPE_CATEGORIES, MEAL_TYPES, Difficulty, IngredientCategory } from '@/types';

const DIFFICULTY_LABEL: Record<Difficulty, string> = { facil: 'Fácil', media: 'Media', dificil: 'Difícil' };

export default function RecipeDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const colors = useThemeColors();
  const recipe = useRecipesStore(s => s.getById(id ?? ''));
  const toggleFavorite = useRecipesStore(s => s.toggleFavorite);
  const deleteRecipe = useRecipesStore(s => s.deleteRecipe);
  const duplicateRecipe = useRecipesStore(s => s.duplicateRecipe);
  const pantryItems = usePantryStore(s => s.items);
  const conversions = useIngredientsStore(s => s.conversions);
  const addShoppingItem = useShoppingStore(s => s.addItem);
  const settings = useSettingsStore(s => s.settings);

  const [servings, setServings] = useState(recipe?.servings ?? 2);
  const [deleteVisible, setDeleteVisible] = useState(false);
  const [toast, setToast] = useState<{ visible: boolean; message: string; type: 'success' | 'error' }>({ visible: false, message: '', type: 'success' });
  const [addingToShopping, setAddingToShopping] = useState(false);

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ visible: true, message, type });
  };

  const availability = useMemo(() => {
    if (!recipe) return null;
    return checkIngredientAvailability(
      recipe.ingredients,
      servings,
      recipe.servings,
      pantryItems,
      conversions
    );
  }, [recipe, servings, pantryItems, conversions]);

  if (!recipe) {
    return (
      <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
        <View style={styles.notFound}>
          <Text style={[styles.notFoundText, { color: colors.text }]}>Receta no encontrada</Text>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={[styles.backLink, { color: colors.primary }]}>Volver</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const categoryInfo = RECIPE_CATEGORIES.find(c => c.value === recipe.category);
  const mealTypeInfo = MEAL_TYPES.find(m => m.value === recipe.mealType);
  const totalTime = recipe.prepTime + recipe.cookTime;

  const handleAddMissingToShopping = async () => {
    if (!availability) return;
    setAddingToShopping(true);
    try {
      const toAdd = [...availability.missing, ...availability.partial];
      for (const ing of toAdd) {
        const avail = availability.availableQty[ing.id] ?? 0;
        const needed = ing.quantity - avail;
        if (needed <= 0) continue;
        await addShoppingItem({
          shoppingListId: '',
          ingredientId: ing.ingredientId ?? null,
          name: ing.name,
          neededQuantity: Math.max(0, needed),
          unit: ing.unit,
          category: 'otros' as IngredientCategory,
          sourceRecipes: JSON.stringify([recipe.name]),
          isAutoGenerated: true,
          isBought: false,
          boughtQuantity: null,
          price: null,
          store: null,
          notes: null,
        });
      }
      showToast(`${toAdd.length} ingredientes añadidos a la compra`);
    } catch (e) {
      showToast('Error al añadir a la compra', 'error');
    } finally {
      setAddingToShopping(false);
    }
  };

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]} edges={['top']}>
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={[styles.heroContainer, { backgroundColor: colors.primarySurface }]}>
          <View style={styles.heroNav}>
            <TouchableOpacity
              style={[styles.iconBtn, { backgroundColor: colors.backgroundCard }]}
              onPress={() => router.back()}
              accessibilityRole="button"
              accessibilityLabel="Volver"
            >
              <Ionicons name="arrow-back" size={20} color={colors.text} />
            </TouchableOpacity>
            <View style={styles.heroActions}>
              <TouchableOpacity
                style={[styles.iconBtn, { backgroundColor: colors.backgroundCard }]}
                onPress={() => toggleFavorite(recipe.id)}
                accessibilityRole="button"
                accessibilityLabel={recipe.isFavorite ? 'Quitar de favoritos' : 'Añadir a favoritos'}
              >
                <Ionicons name={recipe.isFavorite ? 'heart' : 'heart-outline'} size={20} color={recipe.isFavorite ? colors.error : colors.text} />
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.iconBtn, { backgroundColor: colors.backgroundCard }]}
                onPress={() => router.push({ pathname: '/(tabs)/recipes/new', params: { editId: recipe.id } })}
                accessibilityRole="button"
                accessibilityLabel="Editar receta"
              >
                <Ionicons name="pencil-outline" size={20} color={colors.text} />
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.iconBtn, { backgroundColor: colors.backgroundCard }]}
                onPress={() => setDeleteVisible(true)}
                accessibilityRole="button"
                accessibilityLabel="Eliminar receta"
              >
                <Ionicons name="trash-outline" size={20} color={colors.error} />
              </TouchableOpacity>
            </View>
          </View>
          <Text style={styles.heroEmoji}>{categoryInfo?.emoji ?? '🍽️'}</Text>
          <Text style={[styles.heroTitle, { color: colors.text }]}>{recipe.name}</Text>
          {recipe.description && (
            <Text style={[styles.heroDesc, { color: colors.textSecondary }]}>{recipe.description}</Text>
          )}
        </View>

        <View style={styles.content}>
          {/* Stats */}
          <View style={[styles.statsRow, { backgroundColor: colors.backgroundCard }]}>
            <StatItem icon="time-outline" label="Total" value={`${totalTime} min`} color={colors.primary} />
            <StatItem icon="cut-outline" label="Prep" value={`${recipe.prepTime} min`} color={colors.secondary} />
            <StatItem icon="flame-outline" label="Cocción" value={`${recipe.cookTime} min`} color={colors.accent} />
            <StatItem icon="speedometer-outline" label="Dificultad" value={DIFFICULTY_LABEL[recipe.difficulty]} color={colors.info} />
          </View>

          {/* Raciones */}
          <View style={[styles.servingsCard, { backgroundColor: colors.backgroundCard }]}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>Raciones</Text>
            <View style={styles.servingsControl}>
              <TouchableOpacity
                style={[styles.servingsBtn, { borderColor: colors.border }]}
                onPress={() => setServings(Math.max(1, servings - 1))}
                accessibilityRole="button"
                accessibilityLabel="Reducir raciones"
              >
                <Ionicons name="remove" size={20} color={colors.text} />
              </TouchableOpacity>
              <Text style={[styles.servingsNum, { color: colors.primary }]}>{servings}</Text>
              <TouchableOpacity
                style={[styles.servingsBtn, { borderColor: colors.border }]}
                onPress={() => setServings(servings + 1)}
                accessibilityRole="button"
                accessibilityLabel="Aumentar raciones"
              >
                <Ionicons name="add" size={20} color={colors.text} />
              </TouchableOpacity>
            </View>
          </View>

          {/* Disponibilidad de ingredientes */}
          {availability && (
            <View style={[styles.section, { backgroundColor: colors.backgroundCard }]}>
              <View style={styles.sectionHeader}>
                <Text style={[styles.sectionTitle, { color: colors.text }]}>Ingredientes</Text>
                <View style={[styles.compatBadge, {
                  backgroundColor: availability.available.length === recipe.ingredients.length
                    ? colors.successSurface : colors.warningSurface
                }]}>
                  <Text style={[styles.compatText, {
                    color: availability.available.length === recipe.ingredients.length
                      ? colors.success : colors.warning
                  }]}>
                    {Math.round((availability.available.length / recipe.ingredients.filter(i => !i.optional).length) * 100)}%
                  </Text>
                </View>
              </View>

              {availability.available.length > 0 && (
                <IngredientGroup title="Disponible" color={colors.success} icon="checkmark-circle" items={availability.available} availableQty={availability.availableQty} />
              )}
              {availability.partial.length > 0 && (
                <IngredientGroup title="Disponible parcialmente" color={colors.warning} icon="alert-circle" items={availability.partial} availableQty={availability.availableQty} />
              )}
              {availability.missing.length > 0 && (
                <IngredientGroup title="No disponible" color={colors.error} icon="close-circle" items={availability.missing} availableQty={availability.availableQty} />
              )}

              {(availability.missing.length > 0 || availability.partial.length > 0) && (
                <TouchableOpacity
                  style={[styles.addToShoppingBtn, { backgroundColor: colors.primary }]}
                  onPress={handleAddMissingToShopping}
                  disabled={addingToShopping}
                  accessibilityRole="button"
                  accessibilityLabel="Añadir ingredientes que faltan a la compra"
                >
                  <Ionicons name="cart-outline" size={18} color="#FFFFFF" />
                  <Text style={styles.addToShoppingText}>
                    {addingToShopping ? 'Añadiendo...' : 'Añadir los que faltan a la compra'}
                  </Text>
                </TouchableOpacity>
              )}
            </View>
          )}

          {/* Pasos */}
          <View style={[styles.section, { backgroundColor: colors.backgroundCard }]}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>Preparación</Text>
            {recipe.steps.map((step, i) => (
              <View key={step.id} style={styles.stepRow}>
                <View style={[styles.stepNum, { backgroundColor: colors.primary }]}>
                  <Text style={styles.stepNumText}>{step.stepNumber}</Text>
                </View>
                <Text style={[styles.stepText, { color: colors.text }]}>{step.instruction}</Text>
              </View>
            ))}
          </View>

          {/* Notas */}
          {recipe.notes && (
            <View style={[styles.section, { backgroundColor: colors.backgroundCard }]}>
              <Text style={[styles.sectionTitle, { color: colors.text }]}>Notas</Text>
              <Text style={[styles.notesText, { color: colors.textSecondary }]}>{recipe.notes}</Text>
            </View>
          )}

          {/* Añadir al menú */}
          <TouchableOpacity
            style={[styles.addToMenuBtn, { backgroundColor: colors.secondary }]}
            onPress={() => router.push({ pathname: '/modals/add-meal', params: { recipeId: recipe.id } })}
            accessibilityRole="button"
            accessibilityLabel="Añadir al menú semanal"
          >
            <Ionicons name="calendar-outline" size={20} color="#FFFFFF" />
            <Text style={styles.addToMenuText}>Añadir al menú semanal</Text>
          </TouchableOpacity>

          <View style={{ height: 32 }} />
        </View>
      </ScrollView>

      <ConfirmDialog
        visible={deleteVisible}
        title="Eliminar receta"
        message={`¿Estás seguro de que quieres eliminar "${recipe.name}"? Esta acción no se puede deshacer.`}
        confirmText="Eliminar"
        destructive
        onConfirm={async () => {
          await deleteRecipe(recipe.id);
          setDeleteVisible(false);
          router.back();
        }}
        onCancel={() => setDeleteVisible(false)}
      />

      <Toast
        visible={toast.visible}
        message={toast.message}
        type={toast.type}
        onHide={() => setToast(t => ({ ...t, visible: false }))}
      />
    </SafeAreaView>
  );
}

function StatItem({ icon, label, value, color }: { icon: any; label: string; value: string; color: string }) {
  const colors = useThemeColors();
  return (
    <View style={styles.statItem}>
      <Ionicons name={icon} size={20} color={color} />
      <Text style={[styles.statValue, { color: colors.text }]}>{value}</Text>
      <Text style={[styles.statLabel, { color: colors.textTertiary }]}>{label}</Text>
    </View>
  );
}

function IngredientGroup({ title, color, icon, items, availableQty }: { title: string; color: string; icon: any; items: any[]; availableQty: Record<string, number> }) {
  const colors = useThemeColors();
  return (
    <View style={[styles.ingGroup, { borderLeftColor: color }]}>
      <View style={styles.ingGroupHeader}>
        <Ionicons name={icon} size={14} color={color} />
        <Text style={[styles.ingGroupTitle, { color }]}>{title}</Text>
      </View>
      {items.map((ing: any) => {
        const avail = availableQty[ing.id] ?? 0;
        return (
          <View key={ing.id} style={styles.ingRow}>
            <Text style={[styles.ingName, { color: colors.text }]} numberOfLines={1}>{ing.name}</Text>
            <Text style={[styles.ingQty, { color: colors.textSecondary }]}>
              {formatQuantity(ing.quantity, ing.unit)}
              {avail > 0 && avail < ing.quantity && ` (tienes ${formatQuantity(avail, ing.unit)})`}
            </Text>
          </View>
        );
      })}
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  notFoundText: { fontSize: 18, fontWeight: '600' },
  backLink: { fontSize: 15, fontWeight: '600' },
  heroContainer: { padding: 20, alignItems: 'center', paddingBottom: 32 },
  heroNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
    marginBottom: 20,
  },
  heroActions: { flexDirection: 'row', gap: 8 },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  heroEmoji: { fontSize: 56, marginBottom: 12 },
  heroTitle: { fontSize: 24, fontWeight: '800', textAlign: 'center', marginBottom: 8 },
  heroDesc: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  content: { padding: 16, gap: 14 },
  statsRow: {
    flexDirection: 'row',
    borderRadius: 16,
    padding: 16,
    justifyContent: 'space-around',
  },
  statItem: { alignItems: 'center', gap: 4 },
  statValue: { fontSize: 13, fontWeight: '700' },
  statLabel: { fontSize: 11 },
  servingsCard: {
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  servingsControl: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  servingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  servingsNum: { fontSize: 24, fontWeight: '800', minWidth: 32, textAlign: 'center' },
  section: { borderRadius: 16, padding: 16, gap: 12 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionTitle: { fontSize: 17, fontWeight: '700' },
  compatBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  compatText: { fontSize: 13, fontWeight: '700' },
  ingGroup: { borderLeftWidth: 3, paddingLeft: 12, gap: 6 },
  ingGroupHeader: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  ingGroupTitle: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  ingRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  ingName: { flex: 1, fontSize: 14, fontWeight: '500' },
  ingQty: { fontSize: 13 },
  addToShoppingBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 4,
  },
  addToShoppingText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  stepRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  stepNum: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 2,
  },
  stepNumText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  stepText: { flex: 1, fontSize: 14, lineHeight: 22 },
  notesText: { fontSize: 14, lineHeight: 22 },
  addToMenuBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 4,
  },
  addToMenuText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
});
